epochs: 1
log_frequency: 50
sync_bn: false
amp: false
target_text: null
attacker:
  name: PGDLInfinity
  epsilon: 0.047058823529411764
  step_size: 0.00196078431372549
  attack_type: untargeted
dataset:
  name: DatasetGenerator
  train_bs: 128
  eval_bs: 512
  n_workers: 8
  train_d_type: ImageFolder
  test_d_type: ImageFolder
  train_tf_op: CLIPCC3M
  test_tf_op: CLIPCC3M
  train_path: TODO:/PATH/TO/ImageNet/ILSVRC/Data/CLS-LOC
  test_path: TODO:/PATH/TO/ImageNet/ILSVRC/Data/CLS-LOC
  collate_fn:
    name: None
model_list:
- model_name: RN50-quickgelu
  pretrained: cc12m
  cache_dir: TODO:PATH_TO_CACHE_DIR/RN50-quickgelu_cc12m
- model_name: RN50-quickgelu
  pretrained: yfcc15m
  cache_dir: TODO:PATH_TO_CACHE_DIR/RN50-quickgelu_yfcc15m
- model_name: RN101-quickgelu
  pretrained: yfcc15m
  cache_dir: TODO:PATH_TO_CACHE_DIR/RN101-quickgelu_yfcc15m
- model_name: convnext_base
  pretrained: laion400m_s13b_b51k
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_base_laion400m_s13b_b51k
- model_name: convnext_base_w
  pretrained: laion2b_s13b_b82k
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_base_w_laion2b_s13b_b82k
- model_name: convnext_base_w
  pretrained: laion2b_s13b_b82k_augreg
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_base_w_laion2b_s13b_b82k_augreg
- model_name: convnext_base_w
  pretrained: laion_aesthetic_s13b_b82k
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_base_w_laion_aesthetic_s13b_b82k
- model_name: convnext_large_d
  pretrained: laion2b_s26b_b102k_augreg
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_large_d_laion2b_s26b_b102k_augreg
- model_name: convnext_xxlarge
  pretrained: laion2b_s34b_b82k_augreg
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_xxlarge_laion2b_s34b_b82k_augreg
- model_name: convnext_xxlarge
  pretrained: laion2b_s34b_b82k_augreg_rewind
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_xxlarge_laion2b_s34b_b82k_augreg_rewind
- model_name: convnext_xxlarge
  pretrained: laion2b_s34b_b82k_augreg_soup
  cache_dir: TODO:PATH_TO_CACHE_DIR/convnext_xxlarge_laion2b_s34b_b82k_augreg_soup
- model_name: ViT-B-32-quickgelu
  pretrained: laion400m_e31
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32-quickgelu_laion400m_e31
- model_name: ViT-B-32-quickgelu
  pretrained: laion400m_e32
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32-quickgelu_laion400m_e32
- model_name: ViT-B-32
  pretrained: laion2b_e16
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32_laion2b_e16
- model_name: ViT-B-32
  pretrained: laion2b_s34b_b79k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32_laion2b_s34b_b79k
- model_name: ViT-B-32
  pretrained: datacomp_xl_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32_datacomp_xl_s13b_b90k
- model_name: ViT-B-32-quickgelu
  pretrained: metaclip_400m
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32-quickgelu_metaclip_400m
- model_name: ViT-B-32-quickgelu
  pretrained: metaclip_fullcc
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-32-quickgelu_metaclip_fullcc
- model_name: ViT-B-16
  pretrained: laion400m_e31
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16_laion400m_e31
- model_name: ViT-B-16
  pretrained: laion400m_e32
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16_laion400m_e32
- model_name: ViT-B-16
  pretrained: laion2b_s34b_b88k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16_laion2b_s34b_b88k
- model_name: ViT-B-16
  pretrained: datacomp_xl_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16_datacomp_xl_s13b_b90k
- model_name: ViT-B-16
  pretrained: datacomp_l_s1b_b8k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16_datacomp_l_s1b_b8k
- model_name: ViT-B-16
  pretrained: commonpool_l_s1b_b8k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16_commonpool_l_s1b_b8k
- model_name: ViT-B-16-quickgelu
  pretrained: dfn2b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16-quickgelu_dfn2b
- model_name: ViT-B-16-quickgelu
  pretrained: metaclip_400m
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16-quickgelu_metaclip_400m
- model_name: ViT-B-16-quickgelu
  pretrained: metaclip_fullcc
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-B-16-quickgelu_metaclip_fullcc
- model_name: EVA02-B-16
  pretrained: merged2b_s8b_b131k
  cache_dir: TODO:PATH_TO_CACHE_DIR/EVA02-B-16_merged2b_s8b_b131k
- model_name: ViT-L-14
  pretrained: laion400m_e31
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_laion400m_e31
- model_name: ViT-L-14
  pretrained: laion400m_e32
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_laion400m_e32
- model_name: ViT-L-14
  pretrained: laion2b_s32b_b82k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_laion2b_s32b_b82k
- model_name: ViT-L-14
  pretrained: datacomp_xl_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_datacomp_xl_s13b_b90k
- model_name: ViT-L-14
  pretrained: commonpool_xl_clip_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_commonpool_xl_clip_s13b_b90k
- model_name: ViT-L-14
  pretrained: commonpool_xl_laion_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_commonpool_xl_laion_s13b_b90k
- model_name: ViT-L-14
  pretrained: commonpool_xl_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14_commonpool_xl_s13b_b90k
- model_name: ViT-L-14-quickgelu
  pretrained: metaclip_400m
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14-quickgelu_metaclip_400m
- model_name: ViT-L-14-quickgelu
  pretrained: metaclip_fullcc
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14-quickgelu_metaclip_fullcc
- model_name: ViT-L-14-quickgelu
  pretrained: dfn2b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14-quickgelu_dfn2b
- model_name: EVA02-L-14
  pretrained: merged2b_s4b_b131k
  cache_dir: TODO:PATH_TO_CACHE_DIR/EVA02-L-14_merged2b_s4b_b131k
- model_name: ViT-SO400M-14-SigLIP
  pretrained: webli
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-SO400M-14-SigLIP_webli
- model_name: ViT-L-14-CLIPA
  pretrained: datacomp1b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-L-14-CLIPA_datacomp1b
- model_name: ViT-H-14
  pretrained: laion2b_s32b_b79k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-H-14_laion2b_s32b_b79k
- model_name: ViT-H-14-quickgelu
  pretrained: metaclip_fullcc
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-H-14-quickgelu_metaclip_fullcc
- model_name: ViT-H-14-quickgelu
  pretrained: dfn5b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-H-14-quickgelu_dfn5b
- model_name: ViT-g-14
  pretrained: laion2b_s12b_b42k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-g-14_laion2b_s12b_b42k
- model_name: ViT-g-14
  pretrained: laion2b_s34b_b88k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-g-14_laion2b_s34b_b88k
- model_name: EVA02-E-14-plus
  pretrained: laion2b_s9b_b144k
  cache_dir: TODO:PATH_TO_CACHE_DIR/EVA02-E-14-plus_laion2b_s9b_b144k
- model_name: EVA01-g-14-plus
  pretrained: merged2b_s11b_b114k
  cache_dir: TODO:PATH_TO_CACHE_DIR/EVA01-g-14-plus_merged2b_s11b_b114k
- model_name: ViT-bigG-14
  pretrained: laion2b_s39b_b160k
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-bigG-14_laion2b_s39b_b160k
- model_name: ViT-bigG-14-CLIPA
  pretrained: datacomp1b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViT-bigG-14-CLIPA_datacomp1b
- model_name: roberta-ViT-B-32
  pretrained: laion2b_s12b_b32k
  cache_dir: TODO:PATH_TO_CACHE_DIR/roberta-ViT-B-32_laion2b_s12b_b32k
- model_name: xlm-roberta-base-ViT-B-32
  pretrained: laion5b_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/xlm-roberta-base-ViT-B-32_laion5b_s13b_b90k
- model_name: xlm-roberta-large-ViT-H-14
  pretrained: frozen_laion5b_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/xlm-roberta-large-ViT-H-14_frozen_laion5b_s13b_b90k
- model_name: nllb-clip-base
  pretrained: v1
  cache_dir: TODO:PATH_TO_CACHE_DIR/nllb-clip-base_v1
- model_name: nllb-clip-large
  pretrained: v1
  cache_dir: TODO:PATH_TO_CACHE_DIR/nllb-clip-large_v1
- model_name: ViTamin-B
  pretrained: datacomp1b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViTamin-B_datacomp1b
- model_name: ViTamin-B-LTT
  pretrained: datacomp1b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViTamin-B-LTT_datacomp1b
- model_name: ViTamin-L
  pretrained: datacomp1b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViTamin-L_datacomp1b
- model_name: ViTamin-L2
  pretrained: datacomp1b
  cache_dir: TODO:PATH_TO_CACHE_DIR/ViTamin-L2_datacomp1b
- model_name: MobileCLIP-S1
  pretrained: datacompdr
  cache_dir: TODO:PATH_TO_CACHE_DIR/MobileCLIP-S1_datacompdr
- model_name: MobileCLIP-S2
  pretrained: datacompdr
  cache_dir: TODO:PATH_TO_CACHE_DIR/MobileCLIP-S2_datacompdr
- model_name: MobileCLIP-B
  pretrained: datacompdr
  cache_dir: TODO:PATH_TO_CACHE_DIR/MobileCLIP-B_datacompdr
- model_name: coca_ViT-L-14
  pretrained: laion2b_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/coca_ViT-L-14_laion2b_s13b_b90k
- model_name: coca_ViT-B-32
  pretrained: laion2b_s13b_b90k
  cache_dir: TODO:PATH_TO_CACHE_DIR/coca_ViT-B-32_laion2b_s13b_b90k
searcher:
  name: MAB
  rho: 2
  policy: UCB
search_frequency: 5
